# Generate financial time series (FTS) data

In [1]:
import os
import re
import sys
import json
import warnings
import subprocess
import numpy as np
import pandas as pd
import yfinance as yf
import datetime as dt

from tqdm import tqdm
from scipy.optimize import curve_fit
from multiprocessing import Pool, cpu_count

sys.path.append('../modules')
import get_financial_time_series as get_fts

warnings.filterwarnings("ignore")
pd.options.mode.chained_assignment = None
pd.set_option('display.max_columns', None)

## Global variables

In [2]:
input_path_raw = "../input_files/raw_data"
input_path_processed = "../input_files/processed_data"
input_path_data_dictionary = "../input_files/data_dictionary"
output_path = "../output_files"
input_generation_date = "2023-04-11"

In [3]:
# Stock indexes
list_stock_indexes = {
    "^GSPC" : "Standard and Poor's 500", # S&P 500 (United States)
    "^DJI" : "Dow Jones Industrial Average", # Dow Jones Industrial Average (United States)
    "^W5000" : "Wilshire 5000", # Wilshire 5000 (United States)
    "^GSPTSE" : "Toronto Stock Exchange Composite index", # S&P/TSX Composite index (Canada)
    "^GDAXI" : "German Stock index", # DAX Performance index (Germany)
    "^FTSE" : "Financial Times Stock Exchange 100", # FTSE 100 (United Kingdom)
    "^FCHI" : "Continuous Assisted Quotation 40", # CAC 40 (France)
    "^IXIC" : "National Association of Securities Dealers Automated Quotation Composite", # NASDAQ Composite (United States)
    "IMOEX.ME" : "Moscow Stock Exchange", # MOEX Russia Index (Russia)
    "^N225" : "Nikkei Heikin Kabuka Stock Exchange 225", # Nikkei 225 (Japan)
    "^STI" : "Straits Times Index 30", # STI Index (Singapore)
    "^BVSP" : "Sao Paulo Stock Exchange", # IBOVESPA (Brazil)
    "^MERV" : "Buenos Aires Stock Exchange" # MERVAL (Argentine)
}

In [4]:
# Currencies
list_currencies = {
    "KWDUSD=X" : "Currency exchange rate from Kuwaiti Dinar to U.S. dollar", # KWD/USD
    "BHDUSD=X" : "Currency exchange rate from Bahraini Dinar to U.S. dollar", # BHD/USD
    "OMRUSD=X" : "Currency exchange rate from Omani Rial to U.S. dollar", # OMR/USD    
    "JODUSD=X" : "Currency exchange rate from Jordanian Dinar to U.S. dollar", # JOD/USD
    "KYDUSD=X" : "Currency exchange rate from Cayman Islands dollar to U.S. dollar", # KYD/USD
    "GBPUSD=X" : "Currency exchange rate from U.K. pound sterling to U.S. dollar", # GBP/USD
    "CHFUSD=X" : "Currency exchange rate from swiss franc to U.S. dollar", # CHF/USD
    "EURUSD=X" : "Currency exchange rate from euro to U.S. dollar", # EUR/USD
    "SGD=X" : "Currency exchange rate from U.S. dollar to Singapore dollar", # USD/SGD
    "CAD=X" : "Currency exchange rate from U.S. dollar to Canadian dollar", # USD/CAD
    "AUD=X" : "Currency exchange rate from U.S. dollar to Australian dollar", # USD/AUD
    "NZD=X" : "Currency exchange rate from U.S. dollar to New Zealand dollar", # USD/NZD
    "MYR=X" : "Currency exchange rate from U.S. dollar to malaysian ringgit", # USD/MYR    
    "BRL=X" : "Currency exchange rate from U.S. dollar to Brazilian real", # USD/BRL    
    "CNY=X" : "Currency exchange rate from U.S. dollar to chinese renminbi", # USD/CNY
    "HKD=X" : "Currency exchange rate from U.S. dollar to Hong Kong dollar", # USD/HKD
    "SEK=X" : "Currency exchange rate from U.S. dollar to swedish krona", # USD/SEK
    "ZAR=X" : "Currency exchange rate from U.S. dollar to South African rand", # USD/ZAR
    "MXN=X" : "Currency exchange rate from U.S. dollar to mexican peso", # USD/MXN
    "THB=X" : "Currency exchange rate from U.S. dollar to thai baht", # USD/THB
    "PHP=X" : "Currency exchange rate from U.S. dollar to philippines peso", # USD/PHP
    "RUB=X" : "Currency exchange rate from U.S. dollar to russian ruble", # USD/RUB
    "INR=X" : "Currency exchange rate from U.S. dollar to indian rupee", # USD/INR
    "JPY=X" : "Currency exchange rate from U.S. dollar to japanese yen", # USD/JPY    
    "HUF=X" : "Currency exchange rate from U.S. dollar to hungarian forints", # USD/HUF
    "COP=X" : "Currency exchange rate from U.S. dollar to colombian peso", # USD/COP
    "IDR=X" : "Currency exchange rate from U.S. dollar to indonesian rupiah", # USD/IDR
    "EURCOP=X" : "Currency exchange rate from euro to colombian peso" # EUR/COP
}

## Download time series - Stock indexes

In [5]:
df_stock_indexes = get_fts.load_financial_time_series(
    ticker_dict = list_stock_indexes,
    initial_date = "1900-01-01",
    final_date = input_generation_date,
    interval = "1d"
)

[*********************100%***********************]  1 of 1 completed
- Download ^GSPC with initial 23932 rows and 23618 rows after profiling
- Processed ^GSPC : Standard and Poor's 500
[*********************100%***********************]  1 of 1 completed
- Download ^DJI with initial 7876 rows and 7865 rows after profiling
- Processed ^DJI : Dow Jones Industrial Average
[*********************100%***********************]  1 of 1 completed
- Download ^W5000 with initial 8628 rows and 8627 rows after profiling
- Processed ^W5000 : Wilshire 5000
[*********************100%***********************]  1 of 1 completed
- Download ^GSPTSE with initial 10992 rows and 10975 rows after profiling
- Processed ^GSPTSE : Toronto Stock Exchange Composite index
[*********************100%***********************]  1 of 1 completed
- Download ^GDAXI with initial 8916 rows and 8915 rows after profiling
- Processed ^GDAXI : German Stock index
[*********************100%***********************]  1 of 1 completed
- Download ^FTSE with initial 9919 rows and 9899 rows after profiling
- Processed ^FTSE : Financial Times Stock Exchange 100
[*********************100%***********************]  1 of 1 completed
- Download ^FCHI with initial 8404 rows and 8387 rows after profiling
- Processed ^FCHI : Continuous Assisted Quotation 40
[*********************100%***********************]  1 of 1 completed
- Download ^IXIC with initial 13158 rows and 13119 rows after profiling
- Processed ^IXIC : National Association of Securities Dealers Automated Quotation Composite
[*********************100%***********************]  1 of 1 completed
- Download IMOEX.ME with initial 2482 rows and 2480 rows after profiling
- Processed IMOEX.ME : Moscow Stock Exchange
[*********************100%***********************]  1 of 1 completed
- Download ^N225 with initial 14328 rows and 14131 rows after profiling
- Processed ^N225 : Nikkei Heikin Kabuka Stock Exchange 225
[*********************100%***********************]  1 of 1 completed
- Download ^STI with initial 8811 rows and 8790 rows after profiling
- Processed ^STI : Straits Times Index 30
[*********************100%***********************]  1 of 1 completed
- Download ^BVSP with initial 7413 rows and 7393 rows after profiling
- Processed ^BVSP : Sao Paulo Stock Exchange
[*********************100%***********************]  1 of 1 completed
- Download ^MERV with initial 6486 rows and 6467 rows after profiling
- Processed ^MERV : Buenos Aires Stock Exchange

In [6]:
df_stock_indexes

,date,symbol,ticker_name,step,Open,High,Low,Close,Adj Close,Volume,return,log_return,absolute_log_return,log_volatility,cum_log_return,cum_absolute_log_return,cum_log_volatility,cummean_log_return,cummean_absolute_log_return,cummean_log_volatility,cumvariance_log_return,cumvariance_absolute_log_return,cumvariance_log_volatility
0,1928-01-03,^GSPC,Standard and Poor's 500,0,17.760000,17.760000,17.760000,17.760000,17.760000,0,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1928-01-04,^GSPC,Standard and Poor's 500,1,17.719999,17.719999,17.719999,17.719999,17.719999,0,-0.040001,-0.002255,0.002255,3.364917,-0.002255,0.002255,3.364917,-0.001127,0.001127,1.682458,0.000003,0.000003,5.661332
2,1928-01-05,^GSPC,Standard and Poor's 500,2,17.549999,17.549999,17.549999,17.549999,17.549999,0,-0.170000,-0.009640,0.009640,1.963880,-0.011895,0.011895,5.328796,-0.003965,0.003965,1.776265,0.000025,0.000025,2.857065
3,1928-01-06,^GSPC,Standard and Poor's 500,3,17.660000,17.660000,17.660000,17.660000,17.660000,0,0.110001,0.006248,0.006248,1.764805,-0.005647,0.018143,7.093601,-0.001412,0.004536,1.773400,0.000043,0.000018,1.904743
4,1928-01-09,^GSPC,Standard and Poor's 500,4,17.500000,17.500000,17.500000,17.500000,17.500000,0,-0.160000,-0.009101,0.009101,1.658188,-0.014748,0.027244,8.751789,-0.002950,0.005449,1.750358,0.000044,0.000018,1.431212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6462,2023-03-30,^MERV,Buenos Aires Stock Exchange,6480,249104.093750,253322.000000,248221.406250,251639.093750,251639.093750,0,2535.000000,0.010125,0.010125,0.117064,6.067393,109.313479,914.453042,0.000939,0.016914,0.141490,0.003317,0.003031,0.005475
6463,2023-03-31,^MERV,Buenos Aires Stock Exchange,6481,251639.093750,255437.000000,243889.796875,245716.203125,245716.203125,0,-5922.890625,-0.023819,0.023819,0.117989,6.043574,109.337298,914.571032,0.000935,0.016915,0.141487,0.003316,0.003031,0.005474
6464,2023-04-03,^MERV,Buenos Aires Stock Exchange,6482,245716.203125,255141.000000,245716.203125,254696.906250,254696.906250,0,8980.703125,0.035897,0.035897,0.195674,6.079471,109.373195,914.766706,0.000940,0.016918,0.141495,0.003316,0.003031,0.005474
6465,2023-04-04,^MERV,Buenos Aires Stock Exchange,6483,254696.906250,255384.203125,249844.406250,251488.296875,251488.296875,0,-3208.609375,-0.012678,0.012678,0.092488,6.066793,109.385872,914.859193,0.000938,0.016917,0.141488,0.003315,0.003030,0.005474
6466,2023-04-05,^MERV,Buenos Aires Stock Exchange,6484,248918.593750,253467.593750,247592.593750,252848.703125,252848.703125,0,1360.406250,0.005395,0.005395,0.152468,6.072188,109.391267,915.011662,0.000939,0.016915,0.141489,0.003315,0.003030,0.005473

## Download time series - Currencies

In [7]:
df_currencies = get_fts.load_financial_time_series(
    ticker_dict = list_currencies,
    initial_date = "1900-01-01",
    final_date = input_generation_date,
    interval = "1d"
)

[*********************100%***********************]  1 of 1 completed
- Download KWDUSD=X with initial 5014 rows and 4111 rows after profiling
- Processed KWDUSD=X : Currency exchange rate from Kuwaiti Dinar to U.S. dollar
[*********************100%***********************]  1 of 1 completed
- Download BHDUSD=X with initial 5136 rows and 4362 rows after profiling
- Processed BHDUSD=X : Currency exchange rate from Bahraini Dinar to U.S. dollar
[*********************100%***********************]  1 of 1 completed
- Download OMRUSD=X with initial 5040 rows and 3874 rows after profiling
- Processed OMRUSD=X : Currency exchange rate from Omani Rial to U.S. dollar
[*********************100%***********************]  1 of 1 completed
- Download JODUSD=X with initial 5045 rows and 2560 rows after profiling
- Processed JODUSD=X : Currency exchange rate from Jordanian Dinar to U.S. dollar
[*********************100%***********************]  1 of 1 completed
- Download KYDUSD=X with initial 4026 rows and 3466 rows after profiling
- Processed KYDUSD=X : Currency exchange rate from Cayman Islands dollar to U.S. dollar
[*********************100%***********************]  1 of 1 completed
- Download GBPUSD=X with initial 5034 rows and 5011 rows after profiling
- Processed GBPUSD=X : Currency exchange rate from U.K. pound sterling to U.S. dollar
[*********************100%***********************]  1 of 1 completed
- Download CHFUSD=X with initial 5088 rows and 5064 rows after profiling
- Processed CHFUSD=X : Currency exchange rate from swiss franc to U.S. dollar
[*********************100%***********************]  1 of 1 completed
- Download EURUSD=X with initial 5022 rows and 4998 rows after profiling
- Processed EURUSD=X : Currency exchange rate from euro to U.S. dollar
[*********************100%***********************]  1 of 1 completed
- Download SGD=X with initial 5034 rows and 5002 rows after profiling
- Processed SGD=X : Currency exchange rate from U.S. dollar to Singapore dollar
[*********************100%***********************]  1 of 1 completed
- Download CAD=X with initial 5090 rows and 5073 rows after profiling
- Processed CAD=X : Currency exchange rate from U.S. dollar to Canadian dollar
[*********************100%***********************]  1 of 1 completed
- Download AUD=X with initial 4398 rows and 4373 rows after profiling
- Processed AUD=X : Currency exchange rate from U.S. dollar to Australian dollar
[*********************100%***********************]  1 of 1 completed
- Download NZD=X with initial 5023 rows and 4995 rows after profiling
- Processed NZD=X : Currency exchange rate from U.S. dollar to New Zealand dollar
[*********************100%***********************]  1 of 1 completed
- Download MYR=X with initial 5042 rows and 4899 rows after profiling
- Processed MYR=X : Currency exchange rate from U.S. dollar to malaysian ringgit
[*********************100%***********************]  1 of 1 completed
- Download BRL=X with initial 4604 rows and 4536 rows after profiling
- Processed BRL=X : Currency exchange rate from U.S. dollar to Brazilian real
[*********************100%***********************]  1 of 1 completed
- Download CNY=X with initial 5424 rows and 4798 rows after profiling
- Processed CNY=X : Currency exchange rate from U.S. dollar to chinese renminbi
[*********************100%***********************]  1 of 1 completed
- Download HKD=X with initial 5480 rows and 5226 rows after profiling
- Processed HKD=X : Currency exchange rate from U.S. dollar to Hong Kong dollar
[*********************100%***********************]  1 of 1 completed
- Download SEK=X with initial 5481 rows and 5476 rows after profiling
- Processed SEK=X : Currency exchange rate from U.S. dollar to swedish krona
[*********************100%***********************]  1 of 1 completed
- Download ZAR=X with initial 5036 rows and 5030 rows after profiling
- Processed ZAR=X : Currency exchange rate from U.S. dollar to South African rand
[*********************100%***********************]  1 of 1 completed
- Download MXN=X with initial 5043 rows and 5025 rows after profiling
- Processed MXN=X : Currency exchange rate from U.S. dollar to mexican peso
[*********************100%***********************]  1 of 1 completed
- Download THB=X with initial 5021 rows and 4925 rows after profiling
- Processed THB=X : Currency exchange rate from U.S. dollar to thai baht
[*********************100%***********************]  1 of 1 completed
- Download PHP=X with initial 5015 rows and 4579 rows after profiling
- Processed PHP=X : Currency exchange rate from U.S. dollar to philippines peso
[*********************100%***********************]  1 of 1 completed
- Download RUB=X with initial 4913 rows and 4744 rows after profiling
- Processed RUB=X : Currency exchange rate from U.S. dollar to russian ruble
[*********************100%***********************]  1 of 1 completed
- Download INR=X with initial 5019 rows and 4923 rows after profiling
- Processed INR=X : Currency exchange rate from U.S. dollar to indian rupee
[*********************100%***********************]  1 of 1 completed
- Download JPY=X with initial 6856 rows and 6814 rows after profiling
- Processed JPY=X : Currency exchange rate from U.S. dollar to japanese yen
[*********************100%***********************]  1 of 1 completed
- Download HUF=X with initial 5019 rows and 5008 rows after profiling
- Processed HUF=X : Currency exchange rate from U.S. dollar to hungarian forints
[*********************100%***********************]  1 of 1 completed
- Download COP=X with initial 5027 rows and 4823 rows after profiling
- Processed COP=X : Currency exchange rate from U.S. dollar to colombian peso
[*********************100%***********************]  1 of 1 completed
- Download IDR=X with initial 5476 rows and 5354 rows after profiling
- Processed IDR=X : Currency exchange rate from U.S. dollar to indonesian rupiah
[*********************100%***********************]  1 of 1 completed
- Download EURCOP=X with initial 4740 rows and 4622 rows after profiling
- Processed EURCOP=X : Currency exchange rate from euro to colombian peso

In [8]:
df_currencies

,date,symbol,ticker_name,step,Open,High,Low,Close,Adj Close,Volume,return,log_return,absolute_log_return,log_volatility,cum_log_return,cum_absolute_log_return,cum_log_volatility,cummean_log_return,cummean_absolute_log_return,cummean_log_volatility,cumvariance_log_return,cumvariance_absolute_log_return,cumvariance_log_volatility
0,2003-12-03,KWDUSD=X,Currency exchange rate from Kuwaiti Dinar to U...,1,3.416584,3.417752,3.401361,3.401361,3.401361,0,0.005198,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000
1,2003-12-04,KWDUSD=X,Currency exchange rate from Kuwaiti Dinar to U...,2,3.415300,3.415300,3.397316,3.397316,3.397316,0,-0.004044,-0.001190,0.001190,6.678531,-0.001190,0.001190,6.678531,-0.000595,0.000595,3.339265,7.077287e-07,7.077287e-07,22.301385
2,2003-12-05,KWDUSD=X,Currency exchange rate from Kuwaiti Dinar to U...,3,3.410990,3.415651,3.410176,3.414834,3.414834,0,0.017518,0.005143,0.005143,16.580167,0.003953,0.006333,23.258698,0.001318,0.002111,7.752899,1.132868e-05,7.249397e-06,69.591187
3,2003-12-08,KWDUSD=X,Currency exchange rate from Kuwaiti Dinar to U...,4,3.410525,3.418920,3.401361,3.401361,3.401361,0,-0.013474,-0.003953,0.003953,13.369756,0.000000,0.010286,36.628454,0.000000,0.002572,9.157114,1.449879e-05,5.681576e-06,54.281396
4,2003-12-10,KWDUSD=X,Currency exchange rate from Kuwaiti Dinar to U...,6,3.410758,3.412853,3.396162,3.396162,3.396162,0,-0.005198,-0.001529,0.001529,4.140912,-0.001529,0.011816,40.769367,-0.000306,0.002363,8.153873,1.134194e-05,4.478379e-06,45.743501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4617,2023-04-03,EURCOP=X,Currency exchange rate from euro to colombian ...,4733,5019.200195,5019.200195,5019.200195,4999.899902,4999.899902,0,24.899902,0.004993,0.004993,5.100971,0.531064,32.635390,33029.772635,0.000115,0.007067,7.152398,1.013745e-04,5.143450e-05,10.732315
4618,2023-04-04,EURCOP=X,Currency exchange rate from euro to colombian ...,4734,4977.799805,4977.799805,4977.799805,5019.200195,5019.200195,0,19.300293,0.003853,0.003853,6.349658,0.534917,32.639242,33036.122293,0.000116,0.007066,7.152224,1.013556e-04,5.142560e-05,10.730130
4619,2023-04-05,EURCOP=X,Currency exchange rate from euro to colombian ...,4735,4983.700195,4983.700195,4983.700195,4977.799805,4977.799805,0,-41.400391,-0.008283,0.008283,3.905385,0.526634,32.647525,33040.027678,0.000114,0.007067,7.151521,1.013489e-04,5.141479e-05,10.730089
4620,2023-04-06,EURCOP=X,Currency exchange rate from euro to colombian ...,4736,4950.000000,4950.000000,4950.000000,4983.700195,4983.700195,0,5.900391,0.001185,0.001185,8.589950,0.527819,32.648710,33048.617628,0.000114,0.007065,7.151832,1.013272e-04,5.141115e-05,10.728214
4621,2023-04-07,EURCOP=X,Currency exchange rate from euro to colombian ...,4737,4950.000000,4950.000000,4950.000000,4950.000000,4950.000000,0,-33.700195,-0.006785,0.006785,1.879856,0.521034,32.655495,33050.497484,0.000113,0.007065,7.150692,1.013156e-04,5.140004e-05,10.731906

## Save data in input files for no reprocessing

In [9]:
df_stock_indexes.to_csv("{}/df_stock_index_{}.csv".format(input_path_processed, re.sub("-", "", input_generation_date)) , index = False)
df_currencies.to_csv("{}/df_currency_{}.csv".format(input_path_processed, re.sub("-", "", input_generation_date)) , index = False)